let compactCars = [
	{
		name: 'Ford Fiesta',
		model: 'Economy Car',
		img: '../imgs/ford.png',
        personIcon: '../imgs/person.svg',
        AutomaticIcon: '../imgs/automatic.svg',
        personImgIcon: '../imgs/personImg.svg',
        WaterIcon: '../imgs/waterTomchi.svg',
	},
	{
		name: 'Nissan Versa',
		model: 'Compact Car',
		img: '../imgs/vesta.png',
        personIcon: '../imgs/person.svg',
        AutomaticIcon: '../imgs/automatic.svg',
        personImgIcon: '../imgs/personImg.svg',
        WaterIcon: '../imgs/waterTomchi.svg',
	},
	{
		name: 'Toyota Corolla',
		model: 'Mid-size Car',
		img: '../imgs/toyota.png',
        personIcon: '../imgs/person.svg',
        AutomaticIcon: '../imgs/automatic.svg',
        personImgIcon: '../imgs/personImg.svg',
        WaterIcon: '../imgs/waterTomchi.svg',
	},
	{
		name: 'Nissan Rogue',
		model: 'Mid-size SUV',
		img: '../imgs/rogue.png',
        personIcon: '../imgs/person.svg',
        AutomaticIcon: '../imgs/automatic.svg',
        personImgIcon: '../imgs/personImg.svg',
        WaterIcon: '../imgs/waterTomchi.svg',
	},
	{
		name: 'Chevy Traverse',
		model: 'Full-size SUV ',
		img: '../imgs/chevyTravels.png',
        personIcon: '../imgs/person.svg',
        AutomaticIcon: '../imgs/automatic.svg',
        personImgIcon: '../imgs/personImg.svg',
        WaterIcon: '../imgs/waterTomchi.svg',
	},
	{
		name: 'Nissan Altima',
		model: 'Full-size Car',
		img: '../imgs/altima.png',
        personIcon: '../imgs/person.svg',
        AutomaticIcon: '../imgs/automatic.svg',
        personImgIcon: '../imgs/personImg.svg',
        WaterIcon: '../imgs/waterTomchi.svg',
	},
];
let sportsCars = [
	{
		name: 'Royce rolls ghost',
		model: 'Full-size Car',
		img: '../imgs/rollsRoys.png',
        personIcon: '../imgs/person.svg',
        AutomaticIcon: '../imgs/automatic.svg',
        personImgIcon: '../imgs/personImg.svg',
        WaterIcon: '../imgs/waterTomchi.svg',
	},
	{
		name: 'Mercedes s class',
		model: 'Full-size Car',
		img: '../imgs/sClass.png',
        personIcon: '../imgs/person.svg',
        AutomaticIcon: '../imgs/automatic.svg',
        personImgIcon: '../imgs/personImg.svg',
        WaterIcon: '../imgs/waterTomchi.svg',
	},
	{
		name: 'Lamborghini urus',
		model: 'Mid-size Car',
		img: '../imgs/lamborUrus.png',
        personIcon: '../imgs/person.svg',
        AutomaticIcon: '../imgs/automatic.svg',
        personImgIcon: '../imgs/personImg.svg',
        WaterIcon: '../imgs/waterTomchi.svg',
	},
	{
		name: 'Mercedes g63 amg',
		model: 'Mid-size SUV',
		img: '../imgs/amg63.png',
        personIcon: '../imgs/person.svg',
        AutomaticIcon: '../imgs/automatic.svg',
        personImgIcon: '../imgs/personImg.svg',
        WaterIcon: '../imgs/waterTomchi.svg',
	},
];
let vars = [
	{
		name: '15-Passenger Ford Transit ',
		model: 'Full-size Car',
		img: '../imgs/passford15.png',
        personIcon: '../imgs/person.svg',
        AutomaticIcon: '../imgs/automatic.svg',
        personImgIcon: '../imgs/personImg.svg',
        WaterIcon: '../imgs/waterTomchi.svg',
	},
	{
		name: 'Chrysler Pacifica',
		model: 'Full-size Car',
		img: '../imgs/chryslepacifica.png',
        personIcon: '../imgs/person.svg',
        AutomaticIcon: '../imgs/automatic.svg',
        personImgIcon: '../imgs/personImg.svg',
        WaterIcon: '../imgs/waterTomchi.svg',
	},
	{
		name: 'Chevy Silverado 4500HD',
		model: 'Mid-size Car',
		img: '../imgs/chevy4500HD.png',
        personIcon: '../imgs/person.svg',
        AutomaticIcon: '../imgs/automatic.svg',
        personImgIcon: '../imgs/personImg.svg',
        WaterIcon: '../imgs/waterTomchi.svg',
	},
	{
		name: '12-Passenger Ford Transit',
		model: 'Mid-size SUV',
		img: '../imgs/pasford12.png',
        personIcon: '../imgs/person.svg',
        AutomaticIcon: '../imgs/automatic.svg',
        personImgIcon: '../imgs/personImg.svg',
        WaterIcon: '../imgs/waterTomchi.svg',
	},
	{
		name: '15-Passenger Ford Transit ',
		model: 'Mid-size SUV',
		img: '../imgs/pasfordtransit15.png',
        personIcon: '../imgs/person.svg',
        AutomaticIcon: '../imgs/automatic.svg',
        personImgIcon: '../imgs/personImg.svg',
        WaterIcon: '../imgs/waterTomchi.svg',
	},
	{
		name: 'Mercedes-Benz Sprinter',
		model: 'Mid-size SUV',
		img: '../imgs/mersSprin.png',
        personIcon: '../imgs/person.svg',
        AutomaticIcon: '../imgs/automatic.svg',
        personImgIcon: '../imgs/personImg.svg',
        WaterIcon: '../imgs/waterTomchi.svg',
	},
];
